Sprint 9 solution http api
AlexsanderShchetinin/java-kanban pull request #5
Opened 2024-04-13 12:08 UTC by AlexsanderShchetinin

Создан HttpTaskServer для трекера задач

2024-04-14 09:48 UTC, andrew-larkin requested changes
Привет! Очень хорошо, сервер запускается, мы можем создавать задачи и смотреть их. Но есть пара моментов, оставил комментарии по коду. Эти моменты поправить и приложение будет полностью готово.

2024-04-14 09:48 UTC, andrew-larkin commented on src/controller/CommonHandler.java
> +                    if (paths[1].equals("tasks") && paths.length == 3) {    // путь заканчивается id задачи
возвращает не указанную таску, а все таски

2024-04-14 09:48 UTC, andrew-larkin commented on src/controller/CommonHandler.java
> +                case "POST":                // Для запросов типа POST дополнительного разграничения не требуется
при запросе POST создается задача, но при этом в ответе от сервера возвращается ошибка

2024-04-14 09:48 UTC, andrew-larkin commented on src/server/HttpTaskServer.java
> +    HttpServer server;
модификаторы доступа

2024-04-14 14:02 UTC, AlexsanderShchetinin commented on src/controller/CommonHandler.java
> +                    if (paths[1].equals("tasks") && paths.length == 3) {    // путь заканчивается id задачи
У нас в исходных данных написано что когда мы хотим получить определенную задачу, то через / пишем её id, то есть путь получается длиннее на 1. Я это в условии и прописал когда получаю соответствующий эндпоинт, что если массив длиною 2, то он не имеет обращения к определенной таске и мы получаем все в ответ, но если массив из URI равен 3, то тогда идет обращение к таске по id. И если вместо id в запросе будет что то другое, то возвращаю исключение "По данному id ресурс не найден"

Еще раз через отладку посмотрел, все корректно отрабатывает:
например указываю путь tasks/апр или tasks/1
в любом случае получаю эндпоинт который будет в TaskHandler заходить в соответствующий case и там уже запустит метод получения id из URI.
![image](https://github.com/AlexsanderShchetinin/java-kanban/assets/148264133/79b86270-12ff-4c40-9a79-7df01697ec46)

2024-04-14 19:52 UTC, AlexsanderShchetinin commented on src/controller/CommonHandler.java
> +                case "POST":                // Для запросов типа POST дополнительного разграничения не требуется
если правильно понял то ошибка с ответом 500 возникала в случаях когда в теле запроса была указана некорректная задача (подзадача, эпик). Данный недочет исправлен выбросом исключения ManagerSaveException (когда не удается сохранить в память таску из-за некорректных данных) и ответом 400 с подробным текстом.
В след. коммите в класс CommonHandler добавлен метод checkBodyPOST_Request и его вызов перед обработкой POST запросов - в менеджер добавил проверки на исключения при чтении JSON объектов :
- на корректность id эпика (epicId) в подзадаче;
- на корректность поля taskType;
- на корректность поля status;
- на отсутствие значения в поле subtasks у задач и подзадач (всегда должно передаваться null);
- на отсутствие значения в поле epicId у эпиков и задач (всегда должно передаваться 0 или null)

2024-04-14 20:01 UTC, AlexsanderShchetinin commented on src/server/HttpTaskServer.java
> +    HttpServer server;
добавлены

2024-04-15 17:51 UTC, andrew-larkin requested changes
Привет! Нужно доделать создание задачи, сейчас ее создать довольно сложно.

2024-04-15 17:51 UTC, andrew-larkin commented on src/controller/CommonHandler.java
> +            if (jsonObject.get("id").isJsonNull()) {
тут явно ошибка в логике - "при POST запросе поле id должно быть заполнено как null", но если передать null, то будет ошибка)

2024-04-15 17:51 UTC, andrew-larkin commented on src/controller/CommonHandler.java
> +                throw new ParsingException("при POST запросе поле id должно быть заполнено как null");
чтобы создать задачу, должны быть обязательны только name и description, у тебя даже конструктор такой есть - именно так и нужно реализовать создание задачи. все остальные поля, если они не null, уже добавляются опционально

2024-04-15 17:51 UTC, andrew-larkin commented on src/controller/CommonHandler.java
> +                throw new ParsingException("при POST запросе поле id должно быть заполнено как null");
строка 104: идет проверка epicId. но это актуально только для сабтаска. в любых других случаях будет NPE

2024-04-16 09:28 UTC, AlexsanderShchetinin commented on src/controller/CommonHandler.java
> +            if (jsonObject.get("id").isJsonNull()) {
действительно, забыл добавить отрицание.

2024-04-16 15:46 UTC, AlexsanderShchetinin commented on src/controller/CommonHandler.java
> +                throw new ParsingException("при POST запросе поле id должно быть заполнено как null");
оставил проверку только на поля name и description, остальные проверки сделаны точечно при проверках в менеджере

2024-04-17 15:16 UTC, andrew-larkin requested changes
Привет! Ловим NPE, когда пытаемся создать задачу без id. Это нужно поправить. и проверь, пожалуйста, что задача действительно создается только с name и description. и что потом мы сможем ее получить с помощью метода GET tasks/1

2024-04-17 15:16 UTC, andrew-larkin commented on src/controller/CommonHandler.java
> +            if (jsonObject.get("id").isJsonNull()) {
у тебя здесь NPE из-за того что поле id не было передано в json - нужно убрать возможность получения ошибки

2024-04-18 16:03 UTC, merged